[package]
name = "k4dos"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
limine = "0.1.10"
spin = "0.9"
bit_field = "0.10.2"
x86 = "0.52.0"
x86_64 = "0.14.10"