[build]
target = ".cargo/x86_64-kados.json"
rustflags = ["-Cforce-frame-pointers=yes"]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.x86_64-kados]
runner = ".cargo/runner_kvm.sh"